### ISSUE TITLE
1.0.0 Installation problem

### ISSUE THREAD

**Issue by LupusVentus** [League-of-Foundry-Developers/foundryvtt-forien-unidentified-items#38] opened 2023-05-02 15:33 UTC
For some reason can't install the 1.0.0 version. Gives this error in the console:
![image](https://user-images.githubusercontent.com/93127984/235713919-a22853e9-ba26-4991-8619-65305ba48161.png)

Also, in the module browser it still shows up as the previous version.

**Comment by Fridan99** [comment] 2023-05-02 16:12
the same to me.....

**Comment by KammaKhazi** [comment] 2023-05-03 07:09
I had some strange issues also. Hosting via the Forge my module updated fine to v1.0.0 and it initially activated fine and was working on the latest foundry v10 version. But upon logging into my server a second time the module has completed disappeared from the modules list and is no longer present or working. Kind regards and thank you for your hard work.

**Comment by smaskrate** [comment] 2023-05-03 17:53
Just happened to me too. Quick fix for this:

1. Download latest release zip
2. Unzip into old forien-unidentified-items folder ( default %localappdata%/FoundryVTT\Data\modules\forien-unidentified-items )
3. Open module.json with notepad++ or similar
4. Scroll down to the _esmodules_ object and change from:
`    "esmodules": [
        "init.js"
    ],`

to

`    "esmodules": [
        "init.ts"
    ],`

**Comment by MB1997** [comment] 2023-05-04 07:35
Same error here. 
Guess as a Forge user I have to wait for an update. Since the fix seems to be a small one, i hope the Update comes soon.

**Comment by p4535992** [comment] 2023-05-04 11:48
@Varriount  It's seem the github action failed for some issue with the plugin "Publish the release to FoundryVTT's package repository" ?

https://github.com/League-of-Foundry-Developers/foundryvtt-forien-unidentified-items/blob/2ba8dba467a7cdd76220fdef7bb0ff28e166de73/.github/workflows/release.yml#L74

in the meanwhile unistall and install the module with this manifest : [https://github.com/p4535992/foundryvtt-forien-unidentified-items/releases/download/v1.0.0/module.json](https://github.com/p4535992/foundryvtt-forien-unidentified-items/releases/download/v1.0.0/module.json)

**Comment by Varriount** [comment] 2023-05-10 12:43
@p4535992 @LupusVentus Can you try now? For some reason there was an incorrect condition in the "Publish Release" step.

**Comment by p4535992** [comment] 2023-05-10 18:51
> @p4535992 @LupusVentus Can you try now? For some reason there was an incorrect condition in the "Publish Release" step.

There is still some wrong indentation on the yaml at line 74 https://github.com/League-of-Foundry-Developers/foundryvtt-forien-unidentified-items/actions/runs/4937128253/workflow

**Comment by KammaKhazi** [comment] 2023-05-10 20:29
yeah I just tried to update on the forge from p4535992's excellent hot fix above and received the following. it looks like it's installed but in the game server it is not present in the module list and not working as before.
![forien's](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-unidentified-items/assets/81476445/2220f551-73da-46bb-86f6-4f49f81589c9)

**Comment by p4535992** [comment] 2023-05-13 07:23
@Varriount it seem 1.0.3, solved the compilation issue (init.ts now is init.js so the direct json manifest work https://github.com/League-of-Foundry-Developers/foundryvtt-forien-unidentified-items/releases/download/latest/module.json), the problem is with the standard installation module behaviour is miissin the "latest" string or the specific version "v1.0.3" on the url for the manifest.json.
![2023-05-13 09 21 15](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-unidentified-items/assets/5201916/4cdc9588-8483-4992-8592-c12bc66ac908)

**Comment by KammaKhazi** [comment] 2023-05-13 10:18
Just to confirm v1.0.3 has solved my issues on the forge also. Many thanks for your hard work.

**Closed** 2023-05-13 17:49 UTC
Labels: bug
